**UE20CS312 - Data Analytics - Worksheet 5 - Markov Chains abd AB Testing**

*Vijay J, Dept. of CSE - PES2UG20CS815*

#PROBLEMS

##Problem 1 



###Solutions

1) Pij to the nth power or obtain the general formula from the transition matrix's eigenvalues. 

In [43]:
import numpy as np
import pandas as pd

In [44]:

trans_array = np.array([
    [0.002, 0.666, 0.31, 0, 0.022],
    [0.466, 0.102, 0.222, 0, 0.21],
    [0.022, 0.11, 0.502, 0, 0.366],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0, 0.702]
])

assert(trans_array[0].sum() == 1.0)
assert(trans_array[1].sum() == 1.0)
assert(trans_array[2].sum() == 1.0)
assert(trans_array[3].sum() == 1.0)
assert(trans_array[4].sum() == 1.0)


In [45]:
# encoding the initial probability of as a numpy array
res = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(res[0].sum() == 1.0)

In [46]:
mat_D=np.array([0.3,0.4,0.1,0.15,0.05])
mat_E=np.array([
    [0.002, 0.666, 0.31, 0, 0.022],
    [0.466, 0.102, 0.222, 0, 0.21],
    [0.022, 0.11, 0.502, 0, 0.366],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0, 0.702]
])

In [47]:
mat_F=np.dot(mat_D,mat_E)
mat_F

array([0.1947, 0.2577, 0.2353, 0.15  , 0.1623])

2) Because state 4 is a trap state and we cannot travel from it to any other state, the Markov chain is reducible. If all of the states in I interact, the chain is irreducible.

3) What will be the initial probability of a person going to a particular unit after 1 day, 2 days, 10 days, 1000 days, and 1001 days.

In [48]:

mat_F=np.dot(mat_D,mat_E)
mat_F

array([0.1947, 0.2577, 0.2353, 0.15  , 0.1623])

In [49]:

mat_F=mat_D
for i in range(2):
  mat_F=np.dot(mat_F,mat_E)
mat_F

array([0.1435072, 0.2016392, 0.2463988, 0.15     , 0.2584548])

In [50]:
mat_F=mat_D
for i in range(1000):
  mat_F=np.dot(mat_F,mat_E)
mat_F

array([0.1214373 , 0.16411091, 0.19739717, 0.15      , 0.36705462])

In [51]:
mat_F=mat_D
for i in range(1001):
  mat_F=np.dot(mat_F,mat_E)
mat_F

array([0.1214373 , 0.16411091, 0.19739717, 0.15      , 0.36705462])

4) 4) We observe that the probabilities of a person going to a unit after 1000 days are equal to those after 1001 days, i.e., it has reached steady state distribution.

##Problem 2 (3 points)

###Solutions

1) The chain is reducible because the 3rd and 4th states cannot be reached from other states directly or indirectly.

In [52]:
trans_array = np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302],
    [0.466, 0.102, 0.02, 0.032, 0.38],
    [0.0, 0.0, 1, 0.0, 0.0],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0.004, 0.698]
])

assert(trans_array[0].sum() == 1.0)
assert(trans_array[1].sum() == 1.0)
assert(trans_array[2].sum() == 1.0)
assert(trans_array[3].sum() == 1.0)
assert(trans_array[4].sum() == 1.0)


result= np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])
assert(result[0].sum() == 1.0)

In [53]:
#2)
mat_D = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])

mat_E=np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302],
    [0.466, 0.102, 0.02, 0.032, 0.38],
    [0.0, 0.0, 1, 0.0, 0.0],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0.004, 0.698]
])

In [54]:
mat_F=np.dot(mat_D,mat_E)
mat_F

array([[0.1925, 0.2467, 0.1143, 0.169 , 0.2775]])

In [55]:
mat_F=mat_D
for i in range(2):
  mat_F=np.dot(mat_F,mat_E)
mat_F

array([[0.1458722, 0.1872234, 0.139474 , 0.1818544, 0.345576 ]])

In [56]:
mat_F=mat_D
for i in range(1000):
  mat_F=np.dot(mat_F,mat_E)
mat_F

array([[8.97378472e-28, 1.13004326e-27, 6.60595331e-01, 3.39404669e-01,
        2.87688168e-27]])

In [57]:

mat_F=mat_D
for i in range(1001):
  mat_F=np.dot(mat_F,mat_E)
mat_F

array([[8.44851901e-28, 1.06389804e-27, 6.60595331e-01, 3.39404669e-01,
        2.70848815e-27]])

In [58]:
#4)
a=np.array([[ 0 , 1 , 2 , 3]
  ,[ 4 , 5 , 6 , 7]
 ,  [ 8,  9, 10, 11]]
)

In [59]:
mat_D = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])

mat_E=np.array([
    [0.002, 0.666, 0.01, 0.020, 0.302],
    [0.466, 0.102, 0.02, 0.032, 0.38],
    [0.0, 0.0, 1, 0.0, 0.0],
    [0, 0, 0, 1, 0],
    [0.11, 0.122, 0.066, 0.004, 0.698]
])

mat_F = mat_D @ mat_E 
mat_F


array([[0.1925, 0.2467, 0.1143, 0.169 , 0.2775]])

##Problem 3 (3 points)

###Solutions###

In [60]:
#With Santiago
p_amy = np.array([
    [0.002, 0.232, 0.31, 0.434, 0.022],
    [0.426, 0.102, 0.222, 0.04, 0.21],
    [0.03, 0.11, 0.20, 0.294, 0.366],
    [0.003, 0.176, 0.321, 0.3, 0.2],
    [0.11, 0.422, 0.166, 0.1, 0.202]
])

# Without Santiago
p_without_amy = np.array([
    [0.11, 0.222, 0.092, 0.374, 0.202],
    [0.03, 0.11, 0.20, 0.294, 0.366],
    [0.002, 0.232, 0.31, 0.434, 0.022],
    [0.466, 0.102, 0.02, 0.032, 0.38],
    [0.003, 0.176, 0.321, 0.3, 0.2]
])


# encoding the initial probability of as a numpy array
p_b = np.array([[0.3, 0.4, 0.1, 0.15, 0.05]])



In [61]:
p_c=p_b@p_amy
p_c

array([[0.17995, 0.1689 , 0.25825, 0.2256 , 0.1673 ]])

In [62]:
p_c=p_b@p_without_amy
p_c

array([[0.11525, 0.1579 , 0.15765, 0.293  , 0.2762 ]])